Update b2g-gsi-build.yml

diff --git a/.github/workflows/b2g-gsi-build.yml b/.github/workflows/b2g-gsi-build.yml
--- a/.github/workflows/b2g-gsi-build.yml
+++ b/.github/workflows/b2g-gsi-build.yml
@@ -252,89 +252,89 @@ jobs:
 #         git clone https://github.com/ittat/platform_frameworks_base -b ittat-patch-gsi
 #         mv platform_frameworks_base base
         
-    - name: Check The Previous “error.log”
-      run: |
-        if [ -d "${work}/B2G/out" ];then
-          ls -al ${work}/B2G/out/error*
-          echo "old error.log:"
-          cat ${work}/B2G/out/error.log
-          sudo rm ${work}/B2G/out/error.log
-          touch ${work}/B2G/out/error.log
-        fi
+#     - name: Check The Previous “error.log”
+#       run: |
+#         if [ -d "${work}/B2G/out" ];then
+#           ls -al ${work}/B2G/out/error*
+#           echo "old error.log:"
+#           cat ${work}/B2G/out/error.log
+#           sudo rm ${work}/B2G/out/error.log
+#           touch ${work}/B2G/out/error.log
+#         fi
         
-    - name: Build Source Without Gecko
-      if: github.event.action == 'gsi_aosp_build'
-      continue-on-error: true
-      id: build
-      run: |
-        df -h
-        ####
-        cd ${work}
-        sudo rm -rf ./B2G/gonk-misc/Android.mk
-        cp ./Android.mk.gonk.patch B2G/gonk-misc/Android.mk 
+#     - name: Build Source Without Gecko
+#       if: github.event.action == 'gsi_aosp_build'
+#       continue-on-error: true
+#       id: build
+#       run: |
+#         df -h
+#         ####
+#         cd ${work}
+#         sudo rm -rf ./B2G/gonk-misc/Android.mk
+#         cp ./Android.mk.gonk.patch B2G/gonk-misc/Android.mk 
         
-        ####
-        export CCACHE_DIR=~/.ccache
-        /usr/local/bin/ccache  -M 20G
-        /usr/local/bin/ccache -s
-        export USE_CCACHE=1
-        sudo  mv /usr/local/bin/gsed  /usr/local/bin/sed
-        cd ${work}/B2G
-        export DISABLE_SOURCES_XML=true
-        #export SKIP_ABI_CHECKS=true
-        gtimeout 275m ./build.sh -j4 systemimage
-        df -h
+#         ####
+#         export CCACHE_DIR=~/.ccache
+#         /usr/local/bin/ccache  -M 20G
+#         /usr/local/bin/ccache -s
+#         export USE_CCACHE=1
+#         sudo  mv /usr/local/bin/gsed  /usr/local/bin/sed
+#         cd ${work}/B2G
+#         export DISABLE_SOURCES_XML=true
+#         #export SKIP_ABI_CHECKS=true
+#         gtimeout 275m ./build.sh -j4 systemimage
+#         df -h
         
-    - name: B2G Build - Build Source include Gecko
-      if: github.event.action == 'gsi_b2g_build'
-      run: |
-        df -h
-        ####
-        cd ${work}
-        sudo rm -rf ./B2G/gonk-misc/Android.mk
-        cp ./Android.mk.gonk.old B2G/gonk-misc/Android.mk 
+#     - name: B2G Build - Build Source include Gecko
+#       if: github.event.action == 'gsi_b2g_build'
+#       run: |
+#         df -h
+#         ####
+#         cd ${work}
+#         sudo rm -rf ./B2G/gonk-misc/Android.mk
+#         cp ./Android.mk.gonk.old B2G/gonk-misc/Android.mk 
         
-        #sudo rm -rf ./B2G/gonk-misc/api-daemon/Android.mk
-        #cp ./Android.mk.api-daemon.old B2G/gonk-misc/api-daemon/Android.mk 
+#         #sudo rm -rf ./B2G/gonk-misc/api-daemon/Android.mk
+#         #cp ./Android.mk.api-daemon.old B2G/gonk-misc/api-daemon/Android.mk 
 
-        ####
-        cd ${work}
-        mkdir pre-gecko
-        cd pre-gecko
-        rclone copy itd:ci/${image}/b2g-83.0a1.en-US.linux-androideabi-arm.tar.gz ./
+#         ####
+#         cd ${work}
+#         mkdir pre-gecko
+#         cd pre-gecko
+#         rclone copy itd:ci/${image}/b2g-83.0a1.en-US.linux-androideabi-arm.tar.gz ./
           
 
-        ####  build
-        export CCACHE_DIR=~/.ccache
-        /usr/local/bin/ccache  -M 20G
-        /usr/local/bin/ccache -s
-        export USE_CCACHE=1
-        sudo  mv /usr/local/bin/gsed  /usr/local/bin/sed
-        cd ${work}/B2G
-        export DISABLE_SOURCES_XML=true
-        export USE_PREBUILT_B2G=1
-        export PREFERRED_B2G="${work}/pre-gecko/b2g-82.0a1.en-US.linux-androideabi-arm.tar.gz"
-        ./build.sh -j4 systemimage
+#         ####  build
+#         export CCACHE_DIR=~/.ccache
+#         /usr/local/bin/ccache  -M 20G
+#         /usr/local/bin/ccache -s
+#         export USE_CCACHE=1
+#         sudo  mv /usr/local/bin/gsed  /usr/local/bin/sed
+#         cd ${work}/B2G
+#         export DISABLE_SOURCES_XML=true
+#         export USE_PREBUILT_B2G=1
+#         export PREFERRED_B2G="${work}/pre-gecko/b2g-82.0a1.en-US.linux-androideabi-arm.tar.gz"
+#         ./build.sh -j4 systemimage
         
-    - name: Check Current ”error.log“ Status
-#       continue-on-error: true
-      id: check
-      run: |
-        if [ -s ${work}/B2G/out/error.log ]; then
-          echo Error!
-          cat ${work}/B2G/out/error.log
-          today=$(date +%Y-%m-%d)
-          curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=${today}.BuildType.${{github.event.action}}.out${outversion}.error.${{steps.name.build.exitcode}} Error!"
-          cd ~
-          hdiutil detach ${work}
-          sleep 20
-          hdiutil detach ${work}
-          sudo rm -rf ${image}.dmg.sparseimage*
-          df -h
-          exit 211
-        else
-          exit 0
-        fi
+#     - name: Check Current ”error.log“ Status
+# #       continue-on-error: true
+#       id: check
+#       run: |
+#         if [ -s ${work}/B2G/out/error.log ]; then
+#           echo Error!
+#           cat ${work}/B2G/out/error.log
+#           today=$(date +%Y-%m-%d)
+#           curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=${today}.BuildType.${{github.event.action}}.out${outversion}.error.${{steps.name.build.exitcode}} Error!"
+#           cd ~
+#           hdiutil detach ${work}
+#           sleep 20
+#           hdiutil detach ${work}
+#           sudo rm -rf ${image}.dmg.sparseimage*
+#           df -h
+#           exit 211
+#         else
+#           exit 0
+#         fi
         
         
     - name: Repack “b2g-sysroot” for gsi
