Update onyx-build.yml

diff --git a/.github/workflows/onyx-build.yml b/.github/workflows/onyx-build.yml
--- a/.github/workflows/onyx-build.yml
+++ b/.github/workflows/onyx-build.yml
@@ -9,7 +9,7 @@ on:
       
 env:
   SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}} 
-  outversion: ${{ github.event.client_payload.outversion }}  
+#   outversion: ${{ github.event.client_payload.outversion }}  
   action_type: ${{ github.event.action }} 
 
 jobs: 
@@ -48,34 +48,48 @@ jobs:
         brew install rclone
         rclone ls itd:test
            
-#     - name: Fetch source
-#       run: |
-#         df -h
-#         git config --global user.name "ittat"
-#         git config --global user.email "ittat@github.com"
-#         cd /Volumes/android
-#         git clone https://github.com/b2gOS/B2G -b master  --depth=1 
-#         cd ./B2G
-#         echo Download ...
-#         REPO_INIT_FLAGS="--depth=1" REPO_SYNC_FLAGS=" -j128 --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune" ./config.sh onyx
-#         df -h
-
-    - name: Fetch B2G source
+    - name: Fetch source
       run: |
         df -h
         git config --global user.name "ittat"
         git config --global user.email "ittat@github.com"
-        cd ~
-        rclone copy itd:ci/new/android.dmg.sparseimage.zst ./
-        zstd --decompress  android.dmg.sparseimage.zst
-        sudo rm -r ./android.dmg.sparseimage.zst
-        #####mount
-        hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
+        cd /Volumes/android
+        git clone https://github.com/b2gOS/B2G -b master  --depth=1 
+        cd ./B2G
+        echo Download ...
+        REPO_INIT_FLAGS="--depth=1" REPO_SYNC_FLAGS=" -j128 --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune" ./config.sh onyx
         df -h
+
 
     - name: fix soucre
       run: |
-        df -h
+        ####
+        echo apply patch
+        sudo rm -rf ./patcher
+        git clone https://github.com/OnePlus-onyx/patcher -b test
+        ./patcher/patcher.sh 
+        
+        ####
+        cd /Volumes/android/B2G
+        sed -i '' '14d'  system/sepolicy/tests/Android.bp
+        
+        
+        ####
+        cd /Volumes/android/B2G/system
+        sudo rm -rf ./core
+        git clone https://github.com/ReB2GOS/system_core -b gonk-onyx
+        mv system_core core
+        
+        ####
+        cd /Volumes/android/B2G/external
+        sudo rm -rf ./selinux
+        git clone https://github.com/ReB2GOS/external_selinux -b aosp-10.0
+        mv external_selinux selinux
+        cd selinux 
+        git branch test1 c4d3d93c335fbcd34b589b008ee27e5a2a590a43
+        git checkout test1
+        
+        ####
         cd ~
         git clone https://github.com/OnePlus-onyx/build-CI -b b2g
         cd /Volumes/android/
@@ -86,45 +100,13 @@ jobs:
         # Force compressing debug symbols
         cd build/soong
         git am ~/build-CI/0001-gz.patch
-             
+        
+        ####
         df -h
         cd /Volumes/android/B2G
         sudo rm -rf .repo
         df -h
-
-
-#     - name: fix soucre
-#       run: |
-#         ####
-#         cd /Volumes/android/B2G
-#         sed -i '' '14d'  system/sepolicy/tests/Android.bp
-        
-#         ####
-#         echo apply patch
-#         sudo rm -rf ./patcher
-#         git clone https://github.com/OnePlus-onyx/patcher -b test
-#         ./patcher/patcher.sh 
-        
-#         ####     
-#         #df -h
-#         #sudo rm -rf .repo
-#         #df -h
-        
-#         ####
-#         cd /Volumes/android/B2G/system
-#         sudo rm -rf ./core
-#         git clone https://github.com/ReB2GOS/system_core -b gonk-onyx
-#         mv system_core core
-        
-#         ####
-#         cd /Volumes/android/B2G/external
-#         sudo rm -rf ./selinux
-#         git clone https://github.com/ReB2GOS/external_selinux -b aosp-10.0
-#         mv external_selinux selinux
-#         cd selinux 
-#         git branch test1 c4d3d93c335fbcd34b589b008ee27e5a2a590a43
-#         git checkout test1
-        
+           
     - name: repack soucre
       run: |
         hdiutil detach /Volumes/android
@@ -136,18 +118,14 @@ jobs:
       run: |
         df -h
         cd ~
-        #mv ./B2G.tar.zst ./B2G.tar.zst
         rclone copy ./android.dmg.sparseimage.zst itd:ci/new
         df -h
         
-#     - name: send webhook          
-#       run: |
-#         cd /Volumes/android/
-#         curl -H "Authorization: token ${{secrets.GIT_ACCESS_TOKEN}}"   --request POST   --data '{"event_type": "b2g-onyx-part2-build1"}'   https://api.github.com/repos/OnePlus-onyx/build-CI/dispatches
+    - name: send aosp_build webhook          
+      run: |
+        curl -H "Authorization: token ${{secrets.GIT_ACCESS_TOKEN}}"   --request POST   --data '{"event_type": "aosp_build"}'   https://api.github.com/repos/OnePlus-onyx/build-CI/dispatches
    
-
-
-
+   
   aosp_build:
     if: github.event.action == 'aosp_build' || github.event.action == 'test_build' 
     runs-on: macos-latest
@@ -205,48 +183,16 @@ jobs:
         #####mount
         hdiutil attach /Users/runner/android.dmg.sparseimage -mountpoint /Volumes/android
         df -h
-        
-    - name: fix soucre
-      run: |
-        ####
-        echo ${{github.event.action}}
-        if [ ${{github.event.action}} == "aosp_build" ]; then
-            cd ~
-            git clone https://github.com/OnePlus-onyx/build-CI -b b2g
-            cd /Volumes/android/B2G
-            cd gonk-misc
-            git am ~/build-CI/0001-err.patch
-            cd ../
-            # Force compressing debug symbols
-            cd build/soong
-            git am ~/build-CI/0001-gz.patch
-        fi
-        
-        ####
-        df -h
-        
-#     - name: Fetch pre-out source
-#       if: github.event.client_payload.outversion != 1
-#       run: |
-#         cd /Volumes/android/B2G
-#         preoutversion=`expr ${outversion} - 1`
-#         rclone copy itd:ci/new/out${preoutversion}.tar.zst ./
-#         zstd --decompress out${preoutversion}.tar.zst
-#         sudo rm -r ./out${preoutversion}.tar.zst
-#         tar -xvf ./out${preoutversion}.tar ./out
-#         sudo rm -r ./out${preoutversion}.tar
-#         ls ./out
-#         df -h
-    
-    #TODO
+
     - name: move error.log
-      if: github.event.client_payload.outversion != 1
       run: |
-        ls -al /Volumes/android/B2G/out/error*
-        echo "old error.log:"
-        cat /Volumes/android/B2G/out/error.log
-        sudo rm /Volumes/android/B2G/out/error.log
-        touch /Volumes/android/B2G/out/error.log
+        if [ -d "/Volumes/android/B2G/out" ];then
+          ls -al /Volumes/android/B2G/out/error*
+          echo "old error.log:"
+          cat /Volumes/android/B2G/out/error.log
+          sudo rm /Volumes/android/B2G/out/error.log
+          touch /Volumes/android/B2G/out/error.log
+        fi
         
     - name: build soucre
       if: github.event.action == 'aosp_build'
@@ -266,15 +212,21 @@ jobs:
 
     - name: test build soucre
       if: github.event.action == 'test_build'
-#       continue-on-error: true
       run: |
         df -h
         # Download pre-build b2g-bin
         cd /Volumes/android
+        
+        ####
+        sudo rm -rf ./B2G/gonk-misc/Android.mk
+        cp ./Android.mk ./B2G/gonk-misc/
+        
+        ####
         mkdir pre-gecko
         cd pre-gecko
         rclone copy itd:ci/onyx/b2g-82.0a1.en-US.linux-androideabi-arm.tar.gz ./
-        # test build
+        
+        #### test build
         export CCACHE_DIR=~/.ccache
         /usr/local/bin/ccache  -M 70G
         /usr/local/bin/ccache -s
@@ -286,6 +238,8 @@ jobs:
         export PREFERRED_B2G="/Volumes/android/pre-gecko/b2g-82.0a1.en-US.linux-androideabi-arm.tar.gz"
         ./build.sh -j4 dist DIST_DIR=dist_output
         ./build/tools/releasetools/ota_from_target_files dist_output/b2g_onyx-target_files-eng.runner.zip onyx_aosp_ota_update.zip
+        
+        ####
         rclone copy onyx_b2g_ota_update.zip itd:ci/new 
         ls -al dist_output
         ls out/target/product/onyx/system
@@ -293,21 +247,22 @@ jobs:
         df -h
         exit 124
 
-    #TODO
-#     - name: check error.log
-#       id: check
-#       run: |
-#         if [ -s /Volumes/android/B2G/out/error.log ]; then
-#           echo Error!
-#           cat /Volumes/android/B2G/out/error.log
-#           today=$(date +%Y-%m-%d)
-#           curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=${today}.BuildType.${{github.event.action}}.out${outversion}.error.${{steps.name.build.exitcode}} Error!"
-#           exit 2
-#         else
-#           exit 0
-#         fi
+
+    - name: check error.log
+      id: check
+      run: |
+        if [ -s /Volumes/android/B2G/out/error.log ]; then
+          echo Error!
+          cat /Volumes/android/B2G/out/error.log
+          today=$(date +%Y-%m-%d)
+          curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=${today}.BuildType.${{github.event.action}}.out${outversion}.error.${{steps.name.build.exitcode}} Error!"
+          exit 2
+        else
+          exit 0
+        fi
         
     - name: repack sysroot 
+      id: sysroot
       if: steps.check.conclusion == 'success' &&  steps.build.outcome == 'success' && steps.build.conclusion == 'success'
       run: |
         git clone https://github.com/OnePlus-onyx/build-CI -b b2g
@@ -323,42 +278,42 @@ jobs:
         ls -al -h b2g-sysroot.tar.zst
         mv b2g-sysroot.tar.zst /Volumes/android
         df -h
-           
-    - name: remove source exclude out file
+
+    - name: update b2g-sysroot
+      if:  steps.sysroot.conclusion == 'success' &&  steps.check.conclusion == 'success' &&  steps.build.outcome == 'success' && steps.build.conclusion == 'success'
+      run: |
+        cd /Volumes/android/
+        rclone copy b2g-sysroot.tar.zst itd:ci/new
+        sudo rm b2g-sysroot.tar.zst
+
+    - name: repack soucre
       if: steps.check.conclusion == 'success'
       run: |
-        # remove other flier
-        cd /Volumes/android/B2G
-        sudo rm -rf  `ls | grep -v "out" `
-        df -h
-        # repack out 
-        cd /Volumes/android/B2G
-        tar -cvf ./out${outversion}.tar ./out
-        zstd ./out${outversion}.tar
-        sudo rm ./out${outversion}.tar
-        sudo rm -r ./out
-        df -h
+        hdiutil detach /Volumes/android
+        cd ~
+        zstd android.dmg.sparseimage
+        ls -al android.dmg.sparseimage*
+        sudo rm android.dmg.sparseimage
         
-    - name: update 
+    - name: update build source
       if: steps.check.conclusion == 'success'
       run: |
-        cd /Volumes/android/B2G
-        rclone copy ./out${outversion}.tar.zst itd:ci/new 
+        df -h
+        cd ~
+        rclone copy ./android.dmg.sparseimage.zst itd:ci/new
+        df -h
+        sudo rm  -rf ./android.dmg.sparseimage.zst
             
     - name: send aosp_build again
       if: steps.build.outcome == 'failure' && steps.build.conclusion == 'success'  &&  steps.check.conclusion == 'success'         
       run: |
-        cd /Volumes/android/
-        nextoutversion=`expr ${outversion} + 1`
-        curl -H "Authorization: token ${{secrets.GIT_ACCESS_TOKEN}}"   --request POST   --data '{"event_type": "aosp_build", "client_payload": {"outversion":"'${nextoutversion}'"}}'   https://api.github.com/repos/OnePlus-onyx/build-CI/dispatches
-  
-    - name: Send Done Notify & update b2g-sysroot & send build-gecko
+        curl -H "Authorization: token ${{secrets.GIT_ACCESS_TOKEN}}"   --request POST   --data '{"event_type": "aosp_build"}'   https://api.github.com/repos/OnePlus-onyx/build-CI/dispatches
+
+    - name: Send Done Notify & send build-gecko
       if: steps.check.conclusion == 'success' &&  steps.build.outcome == 'success' && steps.build.conclusion == 'success'
       run: |
        curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=${today}.BuildType.${{github.event.action}}.out${outversion}.exitcode.${{steps.name.build.exitcode}} Done!"
-       cd /Volumes/android/
-       rclone copy b2g-sysroot.tar.zst itd:ci/new
-       curl -H "Authorization: token ${{secrets.GIT_ACCESS_TOKEN}}"   --request POST   --data '{"event_type": "gecko_build", "client_payload": {"outversion":"'${outversion}'"}}'   https://api.github.com/repos/OnePlus-onyx/build-CI/dispatches
+       curl -H "Authorization: token ${{secrets.GIT_ACCESS_TOKEN}}"   --request POST   --data '{"event_type": "gecko_build"}'   https://api.github.com/repos/OnePlus-onyx/build-CI/dispatches
    
    
   gecko_build:
@@ -420,16 +375,14 @@ jobs:
         sudo rm b2g-sysroot.tar.zst
         sudo rm mozbuild.tar.bz2
         cd ~
-        #TODO
-        #git clone https://github.com/kaiostech/gecko-b2g -b gonk --depth=1
-        git clone https://github.com/ittat/gecko-b2g-1 -b gonk --depth=1
+        git clone https://github.com/kaiostech/gecko-b2g -b gonk --depth=1
+        #git clone https://github.com/ittat/gecko-b2g-1 -b gonk --depth=1
         df -h
         
     - name: bootstrap source
       run: |
         df -h
-        #TODO
-        cd ~/gecko-b2g-1
+        cd ~/gecko-b2g
         export SHELL=/bin/bash
         export LOCAL_NDK_BASE_URL='ftp://ftp.kaiostech.com/ndk/android-ndk'
         ./mach bootstrap --no-interactive --application-choice 'GeckoView/Firefox for Android'
@@ -438,8 +391,7 @@ jobs:
     - name: Build gecko
       run: |
         df -h
-        #TODO
-        cd ~/gecko-b2g-1
+        cd ~/gecko-b2g
         export SHELL=/bin/bash
         export GONK_PATH=${HOME}/.mozbuild/b2g-sysroot
         export GONK_PRODUCT_NAME=onyx
@@ -461,7 +413,7 @@ jobs:
         name: b2g-82.0a1.en-US.linux-androideabi-arm.tar.gz
         path: ~/.mozbuild/b2g-sysroot/objdir-onyx-gecko/dist/b2g-82.0a1.en-US.linux-androideabi-arm.tar.gz
 
-    - name: update 
+    - name: Upload 
       run: |
         df -h
         cd ~/.mozbuild/b2g-sysroot/objdir-onyx-gecko/dist
@@ -472,6 +424,6 @@ jobs:
       run: |
         today=$(date +%Y-%m-%d)
         curl -X POST "https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage" -d "chat_id=${{secrets.TG_GROUP_KAIOS}}&text=${today}.BuildType.${{github.event.action}}:onyx-build-gecko PASS!"
-        curl -H "Authorization: token ${{secrets.GIT_ACCESS_TOKEN}}"   --request POST   --data '{"event_type": "test_build", "client_payload": {"outversion":"'${outversion}'"}}'   https://api.github.com/repos/OnePlus-onyx/build-CI/dispatches
+        curl -H "Authorization: token ${{secrets.GIT_ACCESS_TOKEN}}"   --request POST   --data '{"event_type": "test_build"}'   https://api.github.com/repos/OnePlus-onyx/build-CI/dispatches
 
   
